---
- name: "calix.yml: gather card types from OLT"
  ansible.netcommon.netconf_rpc:
    rpc: get
    xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
    content: |
      <filter>
          <status xmlns="http://www.calix.com/ns/exa/base">
          <system>
              <card xmlns="http://www.calix.com/ns/exa/equipment-ua"/>
          </system>
          </status>
      </filter>    
    display: json
  register: olt_profile_tool__rpc_get_cards
  failed_when:
    - olt_profile_tool__rpc_get_cards["output"]["rpc-reply"]["data"]["status"]["system"]["card"] is not defined
    - olt_profile_tool__rpc_get_cards["output"]["rpc-reply"]["data"]["status"]["system"]["card"] | length == 0

- name: "calix.yml: set flag for GPON OLT"
  ansible.builtin.set_fact:
    olt_profile_tool__calix_gpon_olt: true
  when: 
    - olt_profile_tool__rpc_get_cards | json_query(olt_profile_tool__json_queries.calix_gpon_cards) | length > 0

- name: "calix.yml: set flag for XGSPON OLT"
  ansible.builtin.set_fact:
    olt_profile_tool__calix_xgspon_olt: true
  when: 
    - olt_profile_tool__rpc_get_cards | json_query(olt_profile_tool__json_queries.calix_xgspon_cards) | length > 0

- name: "calix.yml: verify we've detected an OLT type"
  ansible.builtin.assert:
    that:
      - olt_profile_tool__calix_gpon_olt or olt_profile_tool__calix_xgspon_olt
    fail_msg: "No OLT type detected"
    success_msg: "OLT type detected> GPON: {{ olt_profile_tool__calix_gpon_olt }}, XGSPON: {{ olt_profile_tool__calix_xgspon_olt }}"

- name: "calix.yml: push policy-map configuration to device"
  ansible.netcommon.netconf_rpc:
    rpc: edit-config
    xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
    content: "{{ lookup('file', 'templates/calix/config_policymap.xml') }}"
    display: json
  register: olt_profile_tool__rpc_config_policymap
  failed_when: olt_profile_tool__rpc_config_policymap["output"]["rpc-reply"]["ok"] is not defined
  changed_when: olt_profile_tool__rpc_config_policymap["output"]["rpc-reply"]["ok"] is defined

- name: "calix.yml: gpon configuration block"
  block:
    - name: "calix.yml: push gpon line profiles to device"
      ansible.netcommon.netconf_rpc:
        rpc: edit-config
        xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
        content: "{{ lookup('file', 'templates/calix/config_lineprofile_gpon.xml') }}"
        display: json
      register: olt_profile_tool__rpc_config_gpon_profiles
      failed_when: olt_profile_tool__rpc_config_gpon_profiles["output"]["rpc-reply"]["ok"] is not defined
      changed_when: olt_profile_tool__rpc_config_gpon_profiles["output"]["rpc-reply"]["ok"] is defined
  when: olt_profile_tool__calix_gpon_olt is true
  
- name: "calix.yml: xgspon configuration block"
  block:
    - name: "calix.yml: push xgspon line profiles to device"
      ansible.netcommon.netconf_rpc:
        rpc: edit-config
        xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
        content: "{{ lookup('file', 'templates/calix/config_lineprofile_xgspon.xml') }}"
        display: json
      register: olt_profile_tool__rpc_config_xgspon_profiles
      failed_when: olt_profile_tool__rpc_config_xgspon_profiles["output"]["rpc-reply"]["ok"] is not defined
      changed_when: olt_profile_tool__rpc_config_xgspon_profiles["output"]["rpc-reply"]["ok"] is defined

    - name: "calix.yml: push xgspon ont profiles to device"
      ansible.netcommon.netconf_rpc:
        rpc: edit-config
        xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
        content: "{{ lookup('file', 'templates/calix/config_ontprofile_xgspon.xml') }}"
        display: json
      register: olt_profile_tool__rpc_config_xgspon_profiles
      failed_when: olt_profile_tool__rpc_config_xgspon_profiles["output"]["rpc-reply"]["ok"] is not defined
      changed_when: olt_profile_tool__rpc_config_xgspon_profiles["output"]["rpc-reply"]["ok"] is defined
  when: olt_profile_tool__calix_xgspon_olt is true

- name: "calix.yml: config writer block"
  block:
    - name: "calix.yml: write configuration"
      vars:
        write_success_message: "Copy completed."
      ansible.netcommon.netconf_rpc:
        rpc: copy-running-startup
        xmlns: http://www.calix.com/ns/exa/base
        display: json
      register: olt_profile_tool__copy_run_start_rpc
      failed_when: >-
        olt_profile_tool__copy_run_start_rpc["output"]["rpc-reply"]["status"] != write_success_message
        or olt_profile_tool__copy_run_start_rpc["output"]["rpc-reply"]["status"] is not defined
      changed_when: olt_profile_tool__copy_run_start_rpc["output"]["rpc-reply"]["status"] == write_success_message
  rescue:
    - name: "calix.yml: accept suspect-running config"
      vars:
        write_success_message: "Copy completed."
      ansible.netcommon.netconf_rpc:
        rpc: accept-running-config
        xmlns: http://www.calix.com/ns/exa/base
        display: json
      register: olt_profile_tool__accept_suspect_running_rpc
      failed_when: >-
        olt_profile_tool__accept_suspect_running_rpc["output"]["rpc-reply"]["ok"] is not defined
      changed_when: olt_profile_tool__accept_suspect_running_rpc["output"]["rpc-reply"]["ok"] is defined

    - name: "calix.yml: write configuration"
      vars:
        write_success_message: "Copy completed."
      ansible.netcommon.netconf_rpc:
        rpc: copy-running-startup
        xmlns: http://www.calix.com/ns/exa/base
        display: json
      register: olt_profile_tool__copy_run_start_rpc
      failed_when: >-
        olt_profile_tool__copy_run_start_rpc["output"]["rpc-reply"]["status"] != write_success_message
        or olt_profile_tool__copy_run_start_rpc["output"]["rpc-reply"]["status"] is not defined
      changed_when: olt_profile_tool__copy_run_start_rpc["output"]["rpc-reply"]["status"] == write_success_message
