# Get the current configuration for the target passive software flag
# - Fail if its already set, then use the rescue block to remove it
# Validate we aren't trying to upgrade to the same version
# TODO: Get ONU status and post somewhere
---
- name: "get_pre_checks.yml: check the target passive bank firmware setting | element: {{ target_card }}"
  ansible.netcommon.netconf_rpc:
    rpc: get-config
    xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
    content: "{{ lookup('template', cf_nokia_olt_upgrade__olt_sw['rpc']['getcfg_target_passive_sw']) }}"
    display: json
  register: cf_nokia_olt_upgrade__pre_checks__target_passive_software

- name: "get_pre_checks.yml: remove the existing targeted passive software setting if set | element: {{ target_card }}"
  when: >
        cf_nokia_olt_upgrade__pre_checks__target_passive_software['output']['rpc-reply']['data']
        ['anv:device-manager']['adh:device']['swmgmt:software']['swmgmt:target-passive-software']
        ['swmgmt:file-name'] is defined
  ansible.netcommon.netconf_rpc:
    rpc: edit-config
    xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
    content: "{{ lookup('template', cf_nokia_olt_upgrade__olt_sw['rpc'][target_type]['remove_target_passive_sw']) }}"
    display: json
  register: cf_nokia_olt_upgrade__pre_checks__remove_target_passive_software
