---
- name: "poll_for_reachable.yml: poll the element for reachable status until it becomes reachable | element: {{ target_card }}"
  ansible.netcommon.netconf_rpc:
    rpc: get
    xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
    content: "{{ lookup('template', cf_nokia_olt_upgrade__olt_sw['rpc']['get_device_connection_status']) }}"
    display: json
  register: cf_nokia_olt_upgrade__poll_for_reachable
  until:
    - >
      cf_nokia_olt_upgrade__poll_for_reachable['output']['rpc-reply']['data']
      ['anv:device-manager']['adh:device']['adh:device-state']['adh:reachable']
      == "true"
  retries: "{{ cf_nokia_olt_upgrade__check_timers['reboot']['retries'] }}"
  delay: "{{ cf_nokia_olt_upgrade__check_timers['reboot']['delay'] }}"
