---
- name: "check_software_status.yml: get software layout | element: {{ target_card }}"
  ansible.netcommon.netconf_rpc:
    rpc: get
    xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
    content: "{{ lookup('template', cf_nokia_olt_upgrade__olt_sw['rpc']['get_sw_current_layout']) }}"
    display: json
  register: cf_nokia_olt_upgrade__get_current_software_layout

- name: "get_prechecks.yml: set flag to prevent element from being upgraded (already on that software version) | element: {{ target_card }}"
  when:
    - >
      cf_nokia_olt_upgrade__get_current_software_layout['output']['rpc-reply']['data']
      ['anv:device-manager']['adh:device']['swmgmt:software']['swmgmt:active-software']
      == cf_nokia_olt_upgrade__olt_sw['software_name']
  block:
    - name: "get_prechecks.yml: set condition to skip if we are already on that version | element: {{ target_card }}"
      ansible.builtin.set_fact:
        cf_nokia_olt_upgrade__skip_upgrade_process:
          "{{ cf_nokia_olt_upgrade__skip_upgrade_process | default({}) | combine({target_card: true}) }}"

    - name: "get_prechecks.yml: send message to skip upgrade process | element: {{ target_card }}"
      ansible.builtin.debug:
        msg: "The software version we want to upgrade to is already active on the device, skipping upgrade process"
