galaxy_info:
  author: Simon McKelvey
  description: your role description
  company: CityFibre Ltd.
  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
