---
# vars file for olt_profile_tool
olt_profile_tool__json_queries:
  nokia:
    rpc_get_linecards: >-
      output."rpc-reply".data."anv:device-manager"."adh:device".
      "device-specific-data"."hardware-state".
      component[?state."oper-state" == 'enabled'].name
  calix_gpon_cards: >-
    output."rpc-reply".data.status.system.card[?brief.cardlist."provision-type" == 'GPON-8r2'
    || brief.cardlist."provision-type" == 'GP1611'
    || brief.cardlist."provision-type" == 'GP1612'
    ]
  calix_xgspon_cards: >-
    output."rpc-reply".data.status.system.card[?brief.cardlist."provision-type" == 'NG1601'
    || brief.cardlist."provision-type" == 'XG801'
    || brief.cardlist."provision-type" == 'XG1601'
    || brief.cardlist."provision-type" == 'XG3201'
    ]