---
- name: "fw_download_olt_passive.yml: set passive bank to target software | element: {{ target_card }}"
  vars:
    rpc_content: "{{ lookup('template', cf_nokia_olt_upgrade__olt_sw['rpc']['getcfg_target_passive_sw']) }}"
  ansible.netcommon.netconf_rpc:
    rpc: edit-config
    xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
    content: "{{ lookup('template', cf_nokia_olt_upgrade__olt_sw['rpc'][target_type]['set_target_passive_sw']) }}"
    display: json
  register: cf_nokia_olt_upgrade__fw_download_olt_passive
  changed_when:
    - cf_nokia_olt_upgrade__fw_download_olt_passive['output']['rpc-reply']['ok'] is defined
  failed_when:
    - cf_nokia_olt_upgrade__fw_download_olt_passive['output']['rpc-reply']['ok'] is not defined


- name: "fw_download_olt_passive.yml: keep checking until software is downloaded and valid | element: {{ target_card }}"
  ansible.netcommon.netconf_rpc:
    rpc: get
    xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
    content: "{{ lookup('template', cf_nokia_olt_upgrade__olt_sw['rpc']['get_sw_download_status']) }}"
    display: json
  register: cf_nokia_olt_upgrade__fw_download_olt_passive_state
  failed_when:
    - >
      cf_nokia_olt_upgrade__fw_download_olt_passive_state['output']['rpc-reply']['data']
      ['anv:device-manager']['adh:device']['device-specific-data']['hardware-state']
      ['component']['software']['software']['revisions']['revision'] is not defined
  changed_when:
    - >
      cf_nokia_olt_upgrade__fw_download_olt_passive_state
      | json_query(cf_nokia_olt_upgrade__json_filter.sw_is_valid) == "true"
  until:
    - cf_nokia_olt_upgrade__fw_download_olt_passive_state | json_query(cf_nokia_olt_upgrade__json_filter.sw_is_valid) == "true"
  retries: "{{ cf_nokia_olt_upgrade__check_timers['firmware_download']['retries'] }}"
  delay: "{{ cf_nokia_olt_upgrade__check_timers['firmware_download']['delay'] }}"
