---
- name: "fw_download_olt_active.yml: get software layout | element: {{ target_card }}"
  ansible.netcommon.netconf_rpc:
    rpc: get
    xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
    content: "{{ lookup('template', cf_nokia_olt_upgrade__olt_sw['rpc']['get_sw_current_layout']) }}"
    display: json
  register: cf_nokia_olt_upgrade__current_software_state


- name: "fw_download_olt_active.yml: verify software has been staged | element: {{ target_card }}"
  ansible.builtin.assert:
    that:
      - >
        cf_nokia_olt_upgrade__current_software_state['output']['rpc-reply']['data']
        ['anv:device-manager']['adh:device']['swmgmt:software']['swmgmt:passive-software']
        == cf_nokia_olt_upgrade__olt_sw['software_name']
    success_msg: "The software version we want to upgrade to is on the device passive bank"
    fail_msg: "The software version we want to upgrade to is not on the device passive bank, you must stage this device"


- name: "fw_download_olt_active.yml: set active bank to target software | element: {{ target_card }}"
  ansible.netcommon.netconf_rpc:
    rpc: edit-config
    xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
    content: "{{ lookup('template', cf_nokia_olt_upgrade__olt_sw['rpc'][target_type]['set_target_active_sw']) }}"
    display: json
  register: cf_nokia_olt_upgrade__fw_download_olt_set_active
  changed_when:
    - cf_nokia_olt_upgrade__fw_download_olt_set_active['output']['rpc-reply']['ok'] is defined
  failed_when:
    - cf_nokia_olt_upgrade__fw_download_olt_set_active['output']['rpc-reply']['ok'] is not defined


- name: "fw_download_olt_active.yml: keep checking until software is downloaded and valid | element: {{ target_card }}"
  ansible.netcommon.netconf_rpc:
    rpc: get
    xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
    content: "{{ lookup('template', cf_nokia_olt_upgrade__olt_sw['rpc']['get_sw_download_status']) }}"
    display: json
  register: cf_nokia_olt_upgrade__fw_download_olt_active_state
  failed_when:
    - >
      cf_nokia_olt_upgrade__fw_download_olt_active_state['output']['rpc-reply']['data']
      ['anv:device-manager']['adh:device']['device-specific-data']['hardware-state']
      ['component']['software']['software']['revisions']['revision'] is not defined
  changed_when:
    - >
      cf_nokia_olt_upgrade__fw_download_olt_active_state
      | json_query(cf_nokia_olt_upgrade__json_filter.sw_is_valid) == "true"
  until:
    - cf_nokia_olt_upgrade__fw_download_olt_active_state | json_query(cf_nokia_olt_upgrade__json_filter.sw_is_valid) == "true"
  retries: "{{ cf_nokia_olt_upgrade__check_timers['firmware_download']['retries'] }}"
  delay: "{{ cf_nokia_olt_upgrade__check_timers['firmware_download']['delay'] }}"


- name: "fw_download_olt_active.yml: wait for the element to become unreachable (rebooting) | element: {{ target_card }}"
  ansible.netcommon.netconf_rpc:
    rpc: get
    xmlns: urn:ietf:params:xml:ns:netconf:base:1.0
    content: "{{ lookup('template', cf_nokia_olt_upgrade__olt_sw['rpc']['get_device_connection_status']) }}"
    display: json
  register: cf_nokia_olt_upgrade__poll_for_unreachable
  until:
    - >
      cf_nokia_olt_upgrade__poll_for_unreachable['output']['rpc-reply']['data']
      ['anv:device-manager']['adh:device']['adh:device-state']['adh:reachable']
      == "false"
  retries: "{{ cf_nokia_olt_upgrade__check_timers['poll_for_unreachable']['retries'] }}"
  delay: "{{ cf_nokia_olt_upgrade__check_timers['poll_for_unreachable']['delay'] }}"
