---
# tasks file for cf_nokia_olt_rollback
- name: "main.yml: validate inputs"
  ansible.builtin.include_tasks: validate_inputs.yml

- name: "main.yml: get OLT elements and build job inventory"
  ansible.builtin.include_tasks: get_device_elements.yml

- name: "main.yml: check current software status: NT card"
  vars:
    target_element: "{{ olt_card_inventory['hostname'] }}"
    target_card: "NT"
    target_type: "nt"
  ansible.builtin.include_tasks: check_software_status.yml

- name: "main.yml: check current software status: LT1 card"
  vars:
    target_element: "{{ olt_card_inventory['lt'][0]['card'] }}"
    target_card: "LT1"
    target_type: "lt"
  ansible.builtin.include_tasks: check_software_status.yml

- name: "main.yml: check current software status: LT2 card"
  vars:
    target_element: "{{ olt_card_inventory['lt'][1]['card'] }}"
    target_card: "LT2"
    target_type: "lt"
  ansible.builtin.include_tasks: check_software_status.yml

- name: "main.yml: rollback process: LT1"
  when:
    - cf_nokia_olt_rollback__allow_rollback_process[target_card] is true
  vars:
    target_element: "{{ olt_card_inventory['lt'][0]['card'] }}"
    target_card: "LT1"
    target_type: "lt"
  ansible.builtin.include_tasks: rollback_lt.yml

- name: "main.yml: rollback process: LT2"
  when:
    - cf_nokia_olt_rollback__allow_rollback_process[target_card] is true
  vars:
    target_element: "{{ olt_card_inventory['lt'][1]['card'] }}"
    target_card: "LT2"
    target_type: "lt"
  ansible.builtin.include_tasks: rollback_lt.yml

- name: "main.yml: rollback process: NT"
  when:
    - cf_nokia_olt_rollback__allow_rollback_process[target_card] is true
  vars:
    target_element: "{{ olt_card_inventory['hostname'] }}"
    target_card: "NT"
    target_type: "nt"
  ansible.builtin.include_tasks: rollback_nt.yml
