---
# vars file for cf_nokia_olt_upgrade
# IMPORTANT: Do not remove the anchors, these are used to map the RPCs into specific software types in cf_nokia_olt_upgrade__olt_images
# See README for more information
cf_nokia_olt_upgrade__rpc:
  common: &common_rpc
    get_device_connection_status: "templates/common/get_device_connection_status.jinja2"
    get_linecards: "templates/common/get_linecards.jinja2"
    get_onu_list: "templates/common/get_onu_list.jinja2"
    get_onu_status: "templates/common/get_onu_status.jinja2"
    get_sw_current_layout: "templates/common/get_sw_current_layout.jinja2"
    get_sw_download_status: "templates/common/get_sw_download_status.jinja2"
    getcfg_target_passive_sw: "templates/common/getcfg_target_passive_sw.jinja"
  v22: &v22_rpc
    nt:
      remove_target_passive_sw: "templates/v22/remove_target_passive_sw.jinja2"
      set_target_active_sw: "templates/v22/set_target_active_sw.jinja2"
      set_target_passive_sw: "templates/v22/set_target_passive_sw.jinja2"
    lt:
      remove_target_passive_sw: "templates/v22/remove_target_passive_sw.jinja2"
      set_target_active_sw: "templates/v22/set_target_active_sw.jinja2"
      set_target_passive_sw: "templates/v22/set_target_passive_sw.jinja2"
  v24: &v24_rpc
    nt:
      remove_target_passive_sw: "templates/v24/remove_target_passive_sw.jinja2"
      set_target_active_sw: "templates/v24/set_target_active_sw_nt.jinja2"
      set_target_passive_sw: "templates/v24/set_target_passive_sw.jinja2"
    lt:
      remove_target_passive_sw: "templates/v24/remove_target_passive_sw.jinja2"
      set_target_active_sw: "templates/v24/set_target_active_sw_lt.jinja2"
      set_target_passive_sw: "templates/v24/set_target_passive_sw.jinja2"
# IMPORTANT: Do not remove the anchors, these are used to map the RPCs into specific software types in cf_nokia_olt_upgrade__olt_images
# See README for more information
cf_nokia_olt_upgrade__olt_images:
  v24_6_2:
    image_name: "Lightspan-MF_24.6.2.1-299"
    image_dir: "chassis-software/Lightspan-MF_24.6.2.1-299"
    software_name: "L6GQFC24.299"
    rpc:
      <<: [*common_rpc, *v24_rpc]
  v22_12_mp01:
    image_name: "L6GQAG22.640"
    image_dir: "LS-FX-FWLT-C-and-more/L6GQAG22.640"
    software_name: "L6GQAG22.640"
    rpc:
      <<: [*common_rpc, *v22_rpc]
  v22_12_mp02:
    image_name: "L6GQAG22.667"
    image_dir: "LS-FX-FWLT-C-and-more/L6GQAG22.667"
    software_name: "L6GQAG22.667"
    rpc:
      <<: [*common_rpc, *v22_rpc]

cf_nokia_olt_upgrade__json_filter:
  sw_is_defined: >-
    output."rpc-reply"."data"."anv:device-manager"."adh:device"."device-specific-data"
    ."hardware-state"."component"."software"."software"
    ."revisions".revision[?"product-code" == '{{ cf_nokia_olt_upgrade__olt_sw['software_name'] }}'] | [0]
  sw_is_active: >-
    output."rpc-reply"."data"."anv:device-manager"."adh:device"."device-specific-data"
    ."hardware-state"."component"."software"."software"
    ."revisions".revision[?"product-code" == '{{ cf_nokia_olt_upgrade__olt_sw['software_name'] }}'] | [0]."is-active"
  sw_is_committed: >-
    output."rpc-reply"."data"."anv:device-manager"."adh:device"."device-specific-data"
    ."hardware-state"."component"."software"."software"
    ."revisions".revision[?"product-code" == '{{ cf_nokia_olt_upgrade__olt_sw['software_name'] }}'] | [0]."is-committed"
  sw_is_valid: >-
    output."rpc-reply"."data"."anv:device-manager"."adh:device"."device-specific-data"
    ."hardware-state"."component"."software"."software"
    ."revisions".revision[?"product-code" == '{{ cf_nokia_olt_upgrade__olt_sw['software_name'] }}'] | [0]."is-valid"

cf_nokia_olt_upgrade__valid_admin_state: ["unlocked"]
cf_nokia_olt_upgrade__valid_oper_state: ["enabled"]
cf_nokia_olt_upgrade__valid_standby_state: ["providing-service", "hot-standby"]

cf_nokia_olt_upgrade__check_timers:
  firmware_download:
    retries: 45
    delay: 60
  poll_for_unreachable:
    retries: 45
    delay: 30
  reboot:
    retries: 45
    delay: 60
